version: 3.1.{build}
configuration: release
skip_non_tags: true
image: Visual Studio 2019
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
  project: HoshForm.sln
artifacts:
- path: '\bin\Release\netcoreapp3.1\*'
deploy:
- provider: GitHub
  tag: v3.1.$(appveyor-build-version)
  release: HoshForm_v$(appveyor-build-version)
  auth_token:
    secure: dsahD8lNZdxUJMNtbDkrezhJ3SPCfxwMyaGhYvix3bm+ktKZJgVGFp+N7i7haLvj
  artifact: /.*/
  draft: true
  prerelease: true
  force_update: true
  on:
    branch: master 