version: 3.1.{build}
configuration: release
clone_folder: c:\projects\hoshform
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
before_build:
- cmd: nuget restore
build:
  project: HoshForm.sln
  verbosity: minimal
artifacts:
- path: '\bin\Release\netcoreapp3.1\'
  name: HoshForm.exe
- path: '\bin\Release\netcoreapp3.1\'
  name: HoshForm.dll
- path: '\bin\Release\netcoreapp3.1\'
  name: HoshForm.dll.config
- path: '\bin\Release\netcoreapp3.1\'
  name: HoshForm.runetimeconfig.json
- path: '\bin\Release\netcoreapp3.1\'
  name: Newtonsoft.Json
- path: '\bin\Release\netcoreapp3.1\'
  name: SeleniumExtras.WaitHelpers.dll
- path: '\bin\Release\netcoreapp3.1\'
  name: Webdriver.dll
- path: '\bin\Release\netcoreapp3.1\'
  name: WebDriver.Support.dll
deploy:
- provider: GitHub
  tag: v3.1.2
  release: HoshForm_v3.1.2
  auth_token:
    secure: dsahD8lNZdxUJMNtbDkrezhJ3SPCfxwMyaGhYvix3bm+ktKZJgVGFp+N7i7haLvj
  artifact: HoshForm
  draft: true
  force_update: true
  on:
    C:\projects\hoshform\Debug\netcoreapp3.1: ''